# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29a313e39ec317962d989c33bf3e9701abe67f587dfe863828db136c4c864599a26b20ec6a193bb594a6ca83cd8adb86e1fcc3f376235e4786083fc039e4404

test:
  secret_key_base: 9b16ab69eafb94199942c8233175f0ba692ddd4677b820320c4a1a954f07695e1ab95cf2cc9d8383ec3222408cf2fd5d4ce60696e2aea0060c432eb09e26f1e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
